### ISSUE TITLE
Exception during Serializer generation

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-jackson#55]
Using a POJO as key of a Map will crash the generation.

```
ERROR] error while creating source file org.dominokit.jackson.processor.TypeRegistry$TypeDeserializerNotFoundException: de.gishmo.bug.test.dto.PoJoA
  	at org.dominokit.jackson.processor.TypeRegistry.getKeyDeserializer(TypeRegistry.java:827)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getBasicKeyDeserializer(FieldDeserializersChainBuilder.java:167)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getKeyDeserializer(FieldDeserializersChainBuilder.java:162)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getMapDeserializer(FieldDeserializersChainBuilder.java:153)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getFieldDeserializer(FieldDeserializersChainBuilder.java:91)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getInstance(FieldDeserializersChainBuilder.java:80)
  	at org.dominokit.jackson.processor.deserialization.DeserializerBuilder.buildDeserializerMethod(DeserializerBuilder.java:102)
  	at org.dominokit.jackson.processor.deserialization.DeserializerBuilder.buildDeserializer(DeserializerBuilder.java:63)
  	at org.dominokit.jackson.processor.deserialization.AptDeserializerBuilder.lambda$buildInitDeserializersMethod$8(AptDeserializerBuilder.java:581)
```

The attach small project produces the exception. just ran `mvn clean package`

[test-rest.zip](https://github.com/DominoKit/domino-rest/files/6702328/test-rest.zip)

**Comment by FrankHossfeld** [comment]
Well, of course, that would be cool. On the hand, I think this is quite a unusual case ...
